name: example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  comanda_ui:
    path: ../

  google_fonts: ^2.3.1
  
  flutter:
    sdk: flutter
    


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  # fonts:
  #   - family: Baloo
  #     fonts:
  #       - asset: ../assets/fonts/baloo2/Baloo2-Regular.ttf
  #       - asset: ../assets/fonts/baloo2/Baloo2-Medium.ttf
  #         weight: 500
  #       - asset: ../assets/fonts/baloo2/Baloo2-SemiBold.ttf
  #         weight: 600
  #       - asset: ../assets/fonts/baloo2/Baloo2-Bold.ttf
  #         weight: 700