name: comanda_ui
description: ComandaBet Design System
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  google_fonts: ^2.3.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  # fonts:
  #   - family: Baloo2
  #     fonts:
  #       - asset: assets/fonts/baloo2/Baloo2-Regular.ttf
  #       - asset: assets/fonts/baloo2/Baloo2-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/baloo2/Baloo2-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/baloo2/Baloo2-Bold.ttf
  #         weight: 700